{{- range $name, $config := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $config.containerName }}
  labels:
    app: {{ $config.containerName }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $config.containerName }}
  template:
    metadata:
      labels:
        app: {{ $config.containerName }}
    spec:
      containers:
        - name: {{ $config.containerName }}
          image: {{ $config.image }}:{{ $config.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $config.port }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: {{ $config.containerName }}
{{- end }}
